
export const actions = {
    SET_DIFFICULTY: 'SET_DIFFICULTY',
    SET_MAP: 'SET_MAP',
    SET_COMMAND: 'SET_COMMAND',
    SET_VALIDATION: 'SET_VALIDATION',
    SET_ROTATION: 'SET_ROTATION',
    SHOW_ERROR: 'SHOW_ERROR',
    CLEAR_VALIDATION: 'CLEAR_VALIDATION',
} as const;